#! /usr/bin/env python

print('               .NNNND                         SNNNN')
print('               DNNNNNNNO    =$ODNNDO7:    NNNNNNNN-')
print('               NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO')
print('               NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO')
print('               DNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN=')
print('               :NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN')
print('              7NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN')
print('             =NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNM')
print('             NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN=')
print('            ~NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN')
print('            ZNNNNNNNN~~~~~~~~~~~~~~~~~~~~~~~~:NNNNNNNN')
print('            ZNNNNNN~~~~~:~~~~~~~~~~~~~~~~~:~~~~7NNNNNN')
print('            +NNNNN:~~~. . ~~~~~~~~~~~~~~. ,  ~~~INNNNN')
print('             NNNNM~~~,.777? ~~~~~~~~~~~, 777? ~~~NNNNN')
print('             MNNNM~~~.:777$ ~~~~~~~~~~~.~777$ ~~~NNNN+')
print('  .=7777I?++?INNNN~~~: $77:.~~~~~~~~~~~: 777:.~~~NNNNI??+?I7777=.')
print('        :?$77IZNNN:~~~.    ~~~~~=~~~~~~~. .  ~~~=NNN7I77$I~')
print('?I.            NNNN:~~~~~~~~~~~~==~~~~~~~~~~~~~:NNNN            ?I')
print('                ,NNNO~~~~~~~~~~~7I+~~~~~~~~~~~+NNN?')
print('                   ZNNNN$~:~~~~~~~~~~~~~~:=ONNNN.')
print('              N+I?     +DNNNNNNNNNNNNNNNNNNZ,')
print('               ,NND       ,NNNNNNNNNNNN=')
print('                NN=      +NNNNNNNNNNNNNN7')
print('                 NN~Z   NNNNNNNNNNNNNNNNNN')
print('                 =NNNNN:*.MNNN:MNNZ+NNN,NNN')
print('                   MNNNNNNNNNN MNN$+NNN NNN')
print('                       --. NNN MNN7=NNN NNN')
print('                           NNN MNNI=NNN NNN')
print('                           NNN MNNI-NNN NNN')
print('                           NNN MNNI-NNN NNN')
print('                       :+++NNN+NNN$INNN+NNN+++=')
print('                     ,+++?NNNO+NNN++NNN+$NNNI+++++')
print('                   +++++++I?++NNN++++NNN+++?+++++++++,')
print('                 =++++++++???????++++????????+++++++++++')
print('                  ,+++++++++???????+????????++++++++++')
print('                   ,++++++++???+???+???+???+++++++++,')
print('                      ++++++???+???+???+???+++++++,')
print('                         ,++???+???+???+???++=,')
print('                          OCTOCAT VERSION 1.0.0')
